/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(byte_deinterleaver.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(c0dc7d96e5888a641c6f4f53f7294d17)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/isdbt/byte_deinterleaver.h>
// pydoc.h is automatically generated in the build directory
#include <byte_deinterleaver_pydoc.h>

void bind_byte_deinterleaver(py::module& m)
{

    using byte_deinterleaver    = ::gr::isdbt::byte_deinterleaver;


    py::class_<byte_deinterleaver, gr::block, gr::basic_block,
        std::shared_ptr<byte_deinterleaver>>(m, "byte_deinterleaver", D(byte_deinterleaver))

        .def(py::init(&byte_deinterleaver::make),
           D(byte_deinterleaver,make)
        )
        



        ;




}








