/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(byte_interleaver.h) */
/* BINDTOOL_HEADER_FILE_HASH(fba7cb481ffd846e2f5caef1c4d8149d) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/isdbt/byte_interleaver.h>
// pydoc.h is automatically generated in the build directory
#include <byte_interleaver_pydoc.h>

void bind_byte_interleaver(py::module &m) {

  using byte_interleaver = ::gr::isdbt::byte_interleaver;

  py::class_<byte_interleaver, gr::sync_interpolator,
             std::shared_ptr<byte_interleaver>>(m, "byte_interleaver",
                                                D(byte_interleaver))

      .def(py::init(&byte_interleaver::make), py::arg("mode"),
           py::arg("constellation_size"), py::arg("rate"), py::arg("nsegments"),
           D(byte_interleaver, make))

      ;
}
