/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(carrier_modulation.h)                                      */
/* BINDTOOL_HEADER_FILE_HASH(f7260db1a3660b90e35ae82857ec63ee)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/isdbt/carrier_modulation.h>
// pydoc.h is automatically generated in the build directory
#include <carrier_modulation_pydoc.h>

void bind_carrier_modulation(py::module& m)
{

    using carrier_modulation    = ::gr::isdbt::carrier_modulation;


    py::class_<carrier_modulation, gr::sync_decimator,
        std::shared_ptr<carrier_modulation>>(m, "carrier_modulation", D(carrier_modulation))

        .def(py::init(&carrier_modulation::make),
           py::arg("mode"),
           py::arg("segments"),
           py::arg("constellation_size"),
           D(carrier_modulation,make)
        )
        



        ;




}








