/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(energy_descrambler.h) */
/* BINDTOOL_HEADER_FILE_HASH(b31be5d7bc38b4b39e18cd1bbec11474) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/isdbt/energy_descrambler.h>
// pydoc.h is automatically generated in the build directory
#include <energy_descrambler_pydoc.h>

void bind_energy_descrambler(py::module &m) {

  using energy_descrambler = ::gr::isdbt::energy_descrambler;

  py::class_<energy_descrambler, gr::block, gr::basic_block,
             std::shared_ptr<energy_descrambler>>(m, "energy_descrambler",
                                                  D(energy_descrambler))

      .def(py::init(&energy_descrambler::make), D(energy_descrambler, make))

      ;
}
