/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(energy_dispersal.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(9115de36edd0d618dccd3692445ffa4e)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/isdbt/energy_dispersal.h>
// pydoc.h is automatically generated in the build directory
#include <energy_dispersal_pydoc.h>

void bind_energy_dispersal(py::module& m)
{

    using energy_dispersal    = ::gr::isdbt::energy_dispersal;


    py::class_<energy_dispersal, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<energy_dispersal>>(m, "energy_dispersal", D(energy_dispersal))

        .def(py::init(&energy_dispersal::make),
           py::arg("mode"),
           py::arg("const_size"),
           py::arg("rate"),
           py::arg("nsegments"),
           D(energy_dispersal,make)
        )
        



        ;




}








