/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(frequency_interleaver.h) */
/* BINDTOOL_HEADER_FILE_HASH(2df79c71b5a9eb6c25b36d4ae0cccc9a) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/isdbt/frequency_interleaver.h>
// pydoc.h is automatically generated in the build directory
#include <frequency_interleaver_pydoc.h>

void bind_frequency_interleaver(py::module &m) {

  using frequency_interleaver = ::gr::isdbt::frequency_interleaver;

  py::class_<frequency_interleaver, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<frequency_interleaver>>(m, "frequency_interleaver",
                                                     D(frequency_interleaver))

      .def(py::init(&frequency_interleaver::make), py::arg("oneseg"),
           py::arg("mode"), D(frequency_interleaver, make))

      ;
}
