/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(pilot_signals.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(4f5c3ffd3ce3542e5f5ab2d3499fa76e)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/isdbt/pilot_signals.h>
// pydoc.h is automatically generated in the build directory
#include <pilot_signals_pydoc.h>

void bind_pilot_signals(py::module& m)
{

    using pilot_signals    = ::gr::isdbt::pilot_signals;


    py::class_<pilot_signals, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<pilot_signals>>(m, "pilot_signals", D(pilot_signals))

        .def(py::init(&pilot_signals::make),
           py::arg("mode"),
           D(pilot_signals,make)
        )
        



        ;




}








