/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(time_interleaver.h) */
/* BINDTOOL_HEADER_FILE_HASH(eb6f048a73f405735e9e1d79365f0258) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/isdbt/time_interleaver.h>
// pydoc.h is automatically generated in the build directory
#include <time_interleaver_pydoc.h>

void bind_time_interleaver(py::module &m) {

  using time_interleaver = ::gr::isdbt::time_interleaver;

  py::class_<time_interleaver, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<time_interleaver>>(m, "time_interleaver",
                                                D(time_interleaver))

      .def(py::init(&time_interleaver::make), py::arg("mode"),
           py::arg("segments_A"), py::arg("length_A"), py::arg("segments_B"),
           py::arg("length_B"), py::arg("segments_C"), py::arg("length_C"),
           D(time_interleaver, make))

      ;
}
